server:
  port: 0 #8889

spring:
  application:
    name: eureka-client-account
  main:
    allow-bean-definition-overriding: true


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    hostname: localhost