#info:
#  component: DiscoveryService
#
server:
  port: ${port:8010}

eureka:
  client:
    registerWithEureka: false #  eureka에 등록여부
    fetchRegistry: false # registry의 항목을 로컬로 캐시할지 여부
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
